<?php

namespace Acme\DiggBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends EntityRepository
{
	/**
     *  update totalScore
     *
     * 
     */
    public function updateTotalScore()
    {
		$sum = $this->getFacebookScore() + $this->getTwitterScore() + $this->getDiggScore() + $this->getGoogleScore();
        $this->setTotalScore($sum)
    }


    /**
     * facebookScoreCheck() 
     *
     * 
     */	
	public function facebookScoreCheck() 
	{
		
		// example : http://graph.facebook.com/?ids=http://google.fr/
		// we can retrieve multiple results, see http://graph.facebook.com/?ids=http://google.fr/,http://google.com
		// could be cool to update lots of links at the same time
	
		$facebookUrlAsk = "http://graph.facebook.com/?ids=" . $this->getAddress();

	    $jsonData = file_get_contents($facebookUrlAsk,0,null,null);
	    $jsonAsArray = json_decode($jsonData,true);
	    $lastCounts = (integer) $jsonAsArray[$address]['shares']; 
				// surprisingly, here it's called 'shares' and not 'likes' 
				// although it's the number of likes
		if(not($lastCounts == $this->getFacebookScore())) {
			$this->setFacebookScore($lastCounts);
			$this->updateTotalScore();
		}
	}
	
	
    /**
     * twitterScoreCheck() 
     *
     * 
     */	
	public function twitterScoreCheck() 
	{
		// example : http://otter.topsy.com/stats.js?url=http://qpleple.com
		$twitterUrlAsk = "http://otter.topsy.com/stats.js?url=" . $this->getAddress();
		
		$jsonData = file_get_contents($twitterUrlAsk,0,null,null);
		$jsonAsArray = json_decode($jsonData,true);
		$lastCounts = (integer) $jsonAsArray['response']['all'];
		if(not($lastCounts == $this->getTwitterScore())) {
			$this->setTwitterScore($lastCounts);
			$this->updateTotalScore();
		}
	}
	public function googleScoreCheck() 
	{
		// see for ex http://www.tomanthony.co.uk/blog/google_plus_one_button_seo_count_api/comment-page-1/ for the method
		
		$ch = curl_init();   
	 	curl_setopt($ch, CURLOPT_URL, "https://clients6.google.com/rpc?key=AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ"); 
	 	curl_setopt($ch, CURLOPT_POST, 1);
	 	curl_setopt($ch, CURLOPT_POSTFIELDS, '[{"method":"pos.plusones.get","id":"p","params":{"nolog":true,"id":"' . $this->getAdress() . '","source":"widget","userId":"@viewer","groupId":"@self"},"jsonrpc":"2.0","key":"p","apiVersion":"v1"}]');
	 	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	 	curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-type: application/json'));


	 	$jsonData = curl_exec ($ch);
	 	curl_close ($ch);
	 	$jsonAsArray = json_decode($curl_results, true);

	 	$lastCounts = (integer) $jsonAsArray[0]['result']['metadata']['globalCounts']['count'];

		if(not($lastCounts == $this->getTwitterScore())) {
			$this->setGoogleScore($lastCounts);
			$this->updateTotalScore();
		}
	}
	
}